config/routes.rb
Rails.application.routes.draw do

  get '/' => 'zaseki#index'
  post 'zaseki/new' => 'zaseki#new'
  get 'zaseki/shuffle' => 'zaseki#shuffle'
  delete 'zaseki/delete' => 'zaseki#delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/num.rb
class Num < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/zaseki_controller.rb
class ZasekiController < ApplicationController
  def index
    @name = Num.new
    @num = Num.order("num ASC")
    @num.each do |num|
      case num.num
      when 1
          @zaseki1 = num.name
      when 2
          @zaseki2 = num.name
      when 3
          @zaseki3 = num.name
      when 4
          @zaseki4 = num.name
      when 5
          @zaseki5 = num.name
      when 6
          @zaseki6 = num.name
      when 7
          @zaseki7 = num.name
      when 8
          @zaseki8 = num.name
      when 9
          @zaseki9 = num.name
      when 10
          @zaseki10 = num.name
      when 11
          @zaseki11 = num.name
      when 12
          @zaseki12 = num.name
      when 13
          @zaseki13 = num.name
      end
    end
  end

  def new
    flg = 0
    num2 = Num.all
    if num2.count > 12
      flg = 1
      flash[:notice] = "限界だお"
    end
    while flg == 0
      num1 = rand(13)+1
      flg = 1
      num2.each do |num|
        if num.num == num1
          flg = 0
        end
      end
    end

    Num.new(num:num1,name:params[:name]).save
    redirect_to("/")
  end

  def delete
    Num.delete_all
    redirect_to("/")
  end

  def shuffle
    zasekis = Num.all
    array = []
    update_zaseki = []
    count = 0
    while array.length < 13 do
      flg = 0
      while flg == 0 do
        num = rand(13)+1
        flg = 1
        array.each do |temp|
          if temp == num
            flg = 0
          end
        end
      end
      array.push(num)
    end
    zasekis.each do |zaseki|
      zaseki.num = array[count]
      zaseki.save
      count += 1
    end
    # update_zaseki = zaseki.map do |zaseki|
    #   zaseki.num = array[count]
    #   count++
    # end
    # zaseki.zip(array).each do |zaseki,array|
    #   zaseki.num = array
    #   update_zaseki << zaseki
    # end

    # Num.import update_zaseki, on_duplicate_key_update: [:num]
    redirect_to("/")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zaseki_helper.rb
module ZasekiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomikai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/zaseki/index.html.erb
<h1>飲み会の座席きめまーーーーす</h1>
<table class="ui celled table">
    <tr>
        <td><p><%= @zaseki1 %></p></td>
        <td><p><%= @zaseki2 %></p></td>
        <td><p><%= @zaseki3 %></p></td>
        <td><p><%= @zaseki4 %></p></td>
        <td><p><%= @zaseki5 %></p></td>
        <td><p><%= @zaseki6 %></p></td>
        <td><p></td>
    </tr>
    <tr>
        <td><p><%= @zaseki7 %></p></td>
        <td><p><%= @zaseki8 %></p></td>
        <td><p><%= @zaseki9 %></p></td>
        <td><p><%= @zaseki10 %></p></td>
        <td><p><%= @zaseki11 %></p></td>
        <td><p><%= @zaseki12 %></p></td>
        <td><p><%= @zaseki13 %></p></td>
    </tr>
</table>
<%= form_for(@name,url: zaseki_new_path) do %>
    <p>
    名前:<input type="text" name="name" autofocus>
    </p>
    <p>
        <input type="submit" value="座席を決める！">
    </p>
<% end %>
    <%= button_to("シャッフル","/zaseki/shuffle",method: :get )%>
    <p>
        <%= link_to("リセット","/zaseki/delete",method: :delete)%>
    </p>